Update rust-overlay
Fixes this problem, due to `rust-toolchain.toml` requests newer version
than pinned in flake

```
$ nix build .#gotatun
error:
       … in the condition of the assert statement
         at «github:NixOS/nixpkgs/8bb5646e0bed5dbd3ab08c7a7cc15b75ab4e1d0f?narHash=sha256-SqUuBFjhl/kpDiVaKLQBoD8TLD%2B/cTUzzgVFoaHrkqY%3D»/lib/customisation.nix:430:9:
          429|       drvPath =
          430|         assert condition;
             |         ^
          431|         drv.drvPath;

       … while evaluating a branch condition
         at «github:NixOS/nixpkgs/8bb5646e0bed5dbd3ab08c7a7cc15b75ab4e1d0f?narHash=sha256-SqUuBFjhl/kpDiVaKLQBoD8TLD%2B/cTUzzgVFoaHrkqY%3D»/pkgs/stdenv/generic/check-meta.nix:744:5:
          743|     in
          744|     if validity ? handled then
             |     ^
          745|       validity

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: Stable 1.95.0 is not available
```